const className = {
  '디스트로이어': 'destroyer',
  '워로드': 'warlord',
  '버서커': 'berserker',
  '홀리나이트': 'hollyknight',
  '슬레이어': 'slayer',
  '스트라이커': 'striker',
  '배틀마스터': 'battlemaster',
  '인파이터': 'infighter',
  '기공사': 'soulmaster',
  '창술사': 'lancemaster',
  '데빌헌터': 'devilhunter',
  '블래스터': 'blaster',
  '호크아이': 'hawkeye',
  '스카우터': 'scouter',
  '건슬링어': 'gunslinger',
  '바드': 'bard',
  '서머너': 'surmmoner',
  '아르카나': 'arcana',
  '소서리스': 'sorceress',
  '블레이드': 'blade',
  '데모닉': 'demonic',
  '리퍼': 'reaper',
  '소울이터': 'souleater',
  '도화가': 'artist',
  '기상술사': 'aeromancer',
  '브레이커': 'breaker'
};
