// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL-2vq1tVOu3KqVg53dG69sy7N-j_4MtE',
    appId: '1:538997176638:android:44a29d57f1c650249cd46f',
    messagingSenderId: '538997176638',
    projectId: 'test-6f72e',
    storageBucket: 'test-6f72e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAseaRnNB5eHHa8Nm_LTB_duv-8EFfxa4c',
    appId: '1:538997176638:ios:5fb66a57fd75f8549cd46f',
    messagingSenderId: '538997176638',
    projectId: 'test-6f72e',
    storageBucket: 'test-6f72e.appspot.com',
    iosClientId: '538997176638-s4tb82si2k74338pqv3goercif2oof1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAseaRnNB5eHHa8Nm_LTB_duv-8EFfxa4c',
    appId: '1:538997176638:ios:1f3a1427805abe469cd46f',
    messagingSenderId: '538997176638',
    projectId: 'test-6f72e',
    storageBucket: 'test-6f72e.appspot.com',
    iosClientId: '538997176638-4dq7cuqod1l28k7sqmjgcqunqjv8srk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate.RunnerTests',
  );
}
